apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: test-deployment
  namespace: test-poc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      imagePullSecrets:
        - name: jfrogcred
      containers:
      - name: test
        image: gladman.jfrog.io/valaxy-docker-docker-local/gladman:2.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: CONSUMER_KEY
          value: "sdsdasddsadsadasdasd"
        - name: CONSUMER_SECRET
          value: "sdsdasddsadsadasdasd" 
        - name: CONSUMER_TOKEN
          value: "sdsdasddsadsadasdasd" 
        - name: CONSUMER_TOKEN_SECRET
          value: "sdsdasddsadsadasdasd" 